version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  pre_build:
    commands:
      # Caso não seja possível implementarmos o arquivo .env diretamente na raiz do 
      # repositório, podemos hospedá-los no s3 (deployment-files) com o nome .env.frontend.$ambiente (exemplo .env.frontend.prod) 
      # e baixá-los através da tasks abaixo:
      - aws s3 cp s3://deployments-files/.env.frontend.$ambiente .env

  build:
    commands:
      - npm run-script build

  post_build:
    commands:
      # Deployment da nova versão da aplicação diretamente no s3 público, alterando também 
      # a visibilidade destes novos objetos para "leitura pública" de forma recursiva
      - aws s3 cp build s3://$application_name --recursive --acl public-read